### ISSUE TITLE
The log info from the author is weird 

### ISSUE THREAD

**Issue by puppet101** [IrvingMeng/MagFace#12]
Hi, dear author!
I have downloaded the log file of model 'DP&iResnet50' and 'DDP&iResnet50' in the Readme, but I find the values of loss and feature norm are totally different. Could you please have an analysis about this?

logging info  in 'DP&iRestnet50'
Epoch: [24][11300/11372]	Loss 3.239 (3.159)	
  [debug info]: x_norm mean: 22.36 min: 12.71 max: 30.96
  [debug info]: margin mean: 0.49 min: 0.46 max: 0.52
 
'DDP&iResnet50'
Epoch: [24][11300/11373]	Loss 10.545 (11.059)
  [debug info]: x_norm mean: 33.97 min: 25.64 max: 40.67
  [debug info]: margin mean: 0.53 min: 0.50 max: 0.56

**Comment by IrvingMeng** [comment]
Hi, this is caused by a bug during testing, where the total loss is calculated by `loss=loss_id+num_gpu*lamba_g*loss_mag`. Therefore, the `lambda_g` in the DDP version is actually `num_gpu` times (8 in our implementation) of that in the DP version. 

DDP
```
Epoch: [24][11300/11373] Loss 10.545 (11.059) L_ID 1.470 (1.972) L_mag 1.134359 (1.135842)	
```
DP
```
Epoch: [24][11300/11372] Loss 3.239 (3.159) L_ID 1.573 (1.494) L_mag 1.666522 (1.665718)
```

BTW, the released version does not have the bug.

**Comment by puppet101** [comment]
Thanks for your quick reply!
