### ISSUE TITLE
low performance

### ISSUE THREAD

**Issue by kantengri** [IrvingMeng/MagFace#14]
Hello,
I tried to adapt ArcFace evaluation script for MagFace, you can see it here
https://github.com/kantengri/MagFace/tree/try-arcface-eval

Data & model used:
LFW test dataset (lfw-deepfunneled), resized to 112x112.
list file: lfw_test_pair.txt (from ArcFace)
model magface_epoch_00025.pth (Trained by original codes, https://drive.google.com/file/d/1Bd87admxOZvbIOAyTkGEntsEz3fyMt7H/view?usp=sharing)

test.py (modified) output:
(7696, 512)
total time is 96.21539497375488, average time is 0.20003200618244257
truncating identity_list from 7701 to 7696
skipped 5
lfw face verification accuracy:  0.6071726438698916 threshold:  0.48544353

How the accuracy can be improved ? It's much below declared performance (99.83%, see MagFace paper).

**Comment by IrvingMeng** [comment]
Hi, that may be caused by the different pre-processing ways.
Denote the image as X. The released model requires an input as (X-0)/1 [1], while your script uses (X-127.5)/127.5.

[1] https://github.com/IrvingMeng/MagFace/blob/main/inference/gen_feat.py#L98-L101 
[2] https://github.com/kantengri/MagFace/blob/try-arcface-eval/test.py#L46-L47

**Comment by kantengri** [comment]
Thank you, this does much better:
lfw face verification accuracy:  0.890742285237698 threshold:  0.31156468

**Comment by IrvingMeng** [comment]
> Thank you, this does much better:
> lfw face verification accuracy: 0.890742285237698 threshold: 0.31156468

The acc is still too low from my perspective. Maybe you can use our script to extract features and then evaluate them with your code.
